In [1]:
import numpy as np
import pandas as pd
import os

# Define the dimensions of the matrix
num_rows = 20000
num_cols = 10000
file_name = 'large_random_data.csv'

print(f"Generating a {num_rows}x{num_cols} matrix of random integers...")

# Generate random integers between 0 and 100 (inclusive)
# Using randint is efficient for large arrays
data_matrix = np.random.randint(0, 101, size=(num_rows, num_cols))

print("Converting to DataFrame and saving to CSV...")

# Save the numpy array to a CSV file using pandas for convenience
# Set header=False and index=False to save only the data
# This might take some time and consume significant disk space.
pd.DataFrame(data_matrix).to_csv(file_name, header=False, index=False)

print(f"Data saved to '{file_name}'")
file_size_gb = os.path.getsize(file_name) / (1024**3)
print(f"File size: {file_size_gb:.2f} GB")

Generating a 20000x10000 matrix of random integers...
Converting to DataFrame and saving to CSV...
Data saved to 'large_random_data.csv'
File size: 0.54 GB


In [2]:
import numpy as np

# For demonstration, let's create a smaller sample matrix.
# In a real scenario with the large_random_data.csv, you'd need to load parts of it
# or sample from it if memory is a concern.

# Let's assume our 'first row elements' are from this initial data
initial_data_row = np.array([10, 20, 30, 40])

# Define the number of rows for our new matrix
num_new_rows = 5

# Initialize the new matrix with zeros (or any other placeholder)
# The number of columns will be determined by the length of initial_data_row
matrix_assigned = np.zeros((num_new_rows, len(initial_data_row)), dtype=int)

# Assign the first row of our new matrix
matrix_assigned[0, :] = initial_data_row

# Now, assign subsequent rows based on the first row elements.
# Example: Each subsequent row is twice the first row, plus its row index.
for i in range(1, num_new_rows):
    # This is an example of 'assigning subsequent rows to matrix first row elements'
    # The values for row 'i' are derived from 'initial_data_row'
    matrix_assigned[i, :] = initial_data_row * (i + 1) # Example: multiply by (row_index + 1)

print("Original First Row Elements:", initial_data_row)
print("\nMatrix with subsequent rows assigned based on first row:")
print(matrix_assigned)

# If you wanted to do this with the large_random_data.csv, you would first need to load it:
# You would typically load it in chunks or use a library like Dask for out-of-core processing
# For example, loading only the first row from the large file:
# first_row_from_file = pd.read_csv('large_random_data.csv', nrows=1, header=None).iloc[0].values
# Then you could apply a similar logic to generate subsequent rows based on `first_row_from_file`

Original First Row Elements: [10 20 30 40]

Matrix with subsequent rows assigned based on first row:
[[ 10  20  30  40]
 [ 20  40  60  80]
 [ 30  60  90 120]
 [ 40  80 120 160]
 [ 50 100 150 200]]


In [3]:
import numpy as np

# Sample matrix for demonstration
matrix_to_group = np.array([
    [1, 2, 3, 2],
    [4, 1, 5, 6],
    [7, 8, 3, 1]
])

print("Original Matrix:\n", matrix_to_group)

# Method 1: Group by value (store indices for each unique value)
grouped_elements_by_indices = {}
for r in range(matrix_to_group.shape[0]):
    for c in range(matrix_to_group.shape[1]):
        value = matrix_to_group[r, c]
        if value not in grouped_elements_by_indices:
            grouped_elements_by_indices[value] = []
        grouped_elements_by_indices[value].append((r, c))

print("\nGrouped by value (indices where value appears):")
for value, indices in grouped_elements_by_indices.items():
    print(f"Value {value}: {indices}")

# Method 2: Create sub-matrices for specific values (e.g., all 1s, all 2s)
# This example creates a boolean mask for each value, which can be thought of as a 'group matrix'

unique_values = np.unique(matrix_to_group)
print("\nSub-matrices (Boolean masks) for each unique value:")
for val in unique_values:
    mask = (matrix_to_group == val)
    print(f"Elements equal to {val}:\n{mask.astype(int)}") # Display as int for clarity

Original Matrix:
 [[1 2 3 2]
 [4 1 5 6]
 [7 8 3 1]]

Grouped by value (indices where value appears):
Value 1: [(0, 0), (1, 1), (2, 3)]
Value 2: [(0, 1), (0, 3)]
Value 3: [(0, 2), (2, 2)]
Value 4: [(1, 0)]
Value 5: [(1, 2)]
Value 6: [(1, 3)]
Value 7: [(2, 0)]
Value 8: [(2, 1)]

Sub-matrices (Boolean masks) for each unique value:
Elements equal to 1:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]]
Elements equal to 2:
[[0 1 0 1]
 [0 0 0 0]
 [0 0 0 0]]
Elements equal to 3:
[[0 0 1 0]
 [0 0 0 0]
 [0 0 1 0]]
Elements equal to 4:
[[0 0 0 0]
 [1 0 0 0]
 [0 0 0 0]]
Elements equal to 5:
[[0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]]
Elements equal to 6:
[[0 0 0 0]
 [0 0 0 1]
 [0 0 0 0]]
Elements equal to 7:
[[0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]]
Elements equal to 8:
[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]]


In [4]:
import numpy as np

# Define two matrices of the same dimensions
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)

# Matrix Addition
matrix_sum = matrix_a + matrix_b
print("\nMatrix A + Matrix B:\n", matrix_sum)

# Matrix Subtraction
matrix_difference = matrix_a - matrix_b
print("\nMatrix A - Matrix B:\n", matrix_difference)

# Example of attempting to add/subtract matrices of different shapes (will raise an error)
# matrix_c = np.array([[1, 2], [3, 4]])
# try:
#     matrix_a + matrix_c
# except ValueError as e:
#     print(f"\nError for incompatible shapes: {e}")

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix A + Matrix B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix A - Matrix B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [5]:
import numpy as np

def create_even_corner_sum_matrix(n):
    """
    Creates an n x n square matrix where all 2x2 sub-matrices
    have the sum of opposite corner elements as even.
    """
    # A simple way to satisfy the condition is to fill the matrix
    # with only even numbers (e.g., all 2s, or random even numbers)
    # or only odd numbers. If all elements are even (or all odd),
    # then any sum of two elements will be even.

    # Creating a matrix where all elements are a constant even number
    matrix = np.full((n, n), 2) # All elements are 2 (an even number)

    # Alternatively, you could fill with random even numbers:
    # matrix = np.random.randint(0, 50, size=(n, n)) * 2 # Generates random even numbers

    # Or fill with random odd numbers:
    # matrix = np.random.randint(0, 50, size=(n, n)) * 2 + 1 # Generates random odd numbers

    return matrix

# Example usage:
n_size = 5
even_corner_matrix = create_even_corner_sum_matrix(n_size)
print(f"An {n_size}x{n_size} matrix where all sub-matrices have even corner sums:\n", even_corner_matrix)

# Verification (for a small 2x2 sub-matrix)
# Let's pick a sub-matrix, e.g., starting at (0,0):
# a b
# c d
# a=2, b=2, c=2, d=2
# a+d = 2+2 = 4 (even)
# b+c = 2+2 = 4 (even)

# Pick another sub-matrix, e.g., starting at (1,1):
# matrix = np.array([[2, 2, 2],
#                    [2, 2, 2],
#                    [2, 2, 2]])
# sub_matrix = matrix[1:3, 1:3]
# print("\nExample 2x2 sub-matrix from (1,1):\n", sub_matrix)
# a,b,c,d = sub_matrix[0,0], sub_matrix[0,1], sub_matrix[1,0], sub_matrix[1,1]
# print(f"a={a}, b={b}, c={c}, d={d}")
# print(f"a+d = {a+d} (even)")
# print(f"b+c = {b+c} (even)")

An 5x5 matrix where all sub-matrices have even corner sums:
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [6]:
# Define two 'tuple matrices' (list of tuples) for row-wise addition
tuple_matrix_1 = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

tuple_matrix_2 = (
    (10, 11, 12),
    (13, 14, 15),
    (16, 17, 18)
)

print("Tuple Matrix 1:\n", tuple_matrix_1)
print("\nTuple Matrix 2:\n", tuple_matrix_2)

# Perform row-wise element addition
# We iterate through rows and then through elements within each row
# Note: This assumes both matrices have the same number of rows and columns.

result_tuple_matrix = []
num_rows_1 = len(tuple_matrix_1)
num_cols_1 = len(tuple_matrix_1[0])

num_rows_2 = len(tuple_matrix_2)
num_cols_2 = len(tuple_matrix_2[0])

if num_rows_1 != num_rows_2 or num_cols_1 != num_cols_2:
    print("Error: Matrices must have the same dimensions for row-wise addition.")
else:
    for r_idx in range(num_rows_1):
        current_row_result = []
        for c_idx in range(num_cols_1):
            sum_element = tuple_matrix_1[r_idx][c_idx] + tuple_matrix_2[r_idx][c_idx]
            current_row_result.append(sum_element)
        result_tuple_matrix.append(tuple(current_row_result)) # Convert list to tuple for the row

    # Convert the list of tuples back into a single tuple of tuples if desired
    result_tuple_matrix = tuple(result_tuple_matrix)

    print("\nResult of Row-wise Element Addition (Tuple Matrix):\n", result_tuple_matrix)

# For comparison, using numpy for this operation is much simpler and faster:
# np_matrix_1 = np.array(tuple_matrix_1)
# np_matrix_2 = np.array(tuple_matrix_2)
# np_sum = np_matrix_1 + np_matrix_2
# print("\nResult using NumPy (for comparison):\n", np_sum)

Tuple Matrix 1:
 ((1, 2, 3), (4, 5, 6), (7, 8, 9))

Tuple Matrix 2:
 ((10, 11, 12), (13, 14, 15), (16, 17, 18))

Result of Row-wise Element Addition (Tuple Matrix):
 ((11, 13, 15), (17, 19, 21), (23, 25, 27))
